### ISSUE TITLE
Unable to determine shard id for strange mal-formed URL

### ISSUE THREAD

**Issue by wwaites** [paracrawl/giashard#1]
$ giashardid 'www.reddit.com/login/?dest=https%3a%2f%2fwww.reddit.com%2fsubmit%3furl%3dhttp%3a%2f%2fdiyself.gr%2f%25ce%25b4%25ce%25b9%25cf%258e%25ce%25be%25cf%2584%25ce%25b5-%25cf%2584%25ce%25b9%25cf%2582-%25ce%25b3%25ce%25ac%25cf%2584%25ce%25b5%25cf%2582-%25ce%25bc%25ce%25b5-%25ce%25b5%25cf%2585%25ce%25b3%25ce%25b5%25ce%25bd%25ce%25b9%25ce%25ba%25cf%258c-%25cf%2584%25cf%2581%25cf%258c%25cf%2580%25ce%25bf-%25ce%25b1%25cf%2580%25cf%258c%2f%26title%3d%25ce%2594%25ce%25b9%25cf%258e%25ce%25be%25cf%2584%25ce%25b5%2520%25cf%2584%25ce%25b9%25cf%2582%2520%25ce%25b3%25ce%25ac%25cf%2584%25ce%25b5%25cf%2582%2520%25ce%25bc%25ce%25b5%2520%25ce%25b5%25cf%2585%25ce%25b3%25ce%25b5%25ce%25bd%25ce%25b9%25ce%25ba%25cf%258c%2520%25cf%2584%25cf%2581%25cf%258c%25cf%2580%25ce%25bf%2520%25ce%25b1%25cf%2580%25cf%258c%2520%25cf%2584%25ce%25b1%2520%25ce%25bb%25ce%25bf%25cf%2585%25ce%25bb%25ce%25bf%25cf%258d%25ce%25b4%25ce%25b9%25ce%25b1%2520%25cf%2583%25ce%25b1%25cf%2582.'
    2020/02/28 09:39:04 main.go:61: Error computing shard id: www.reddit.com/login/?dest=https%3a%2f%2fwww.reddit.com%2fsubmit%3furl%3dhttp%3a%2f%2fdiyself.gr%2f%25ce%25b4%25ce%25b9%25cf%258e%25ce%25be%25cf%2584%25ce%25b5-%25cf%2584%25ce%25b9%25cf%2582-%25ce%25b3%25ce%25ac%25cf%2584%25ce%25b5%25cf%2582-%25ce%25bc%25ce%25b5-%25ce%25b5%25cf%2585%25ce%25b3%25ce%25b5%25ce%25bd%25ce%25b9%25ce%25ba%25cf%258c-%25cf%2584%25cf%2581%25cf%258c%25cf%2580%25ce%25bf-%25ce%25b1%25cf%2580%25cf%258c%2f%26title%3d%25ce%2594%25ce%25b9%25cf%258e%25ce%25be%25cf%2584%25ce%25b5%2520%25cf%2584%25ce%25b9%25cf%2582%2520%25ce%25b3%25ce%25ac%25cf%2584%25ce%25b5%25cf%2582%2520%25ce%25bc%25ce%25b5%2520%25ce%25b5%25cf%2585%25ce%25b3%25ce%25b5%25ce%25bd%25ce%25b9%25ce%25ba%25cf%258c%2520%25cf%2584%25cf%2581%25cf%258c%25cf%2580%25ce%25bf%2520%25ce%25b1%25cf%2580%25cf%258c%2520%25cf%2584%25ce%25b1%2520%25ce%25bb%25ce%25bf%25cf%2585%25ce%25bb%25ce%25bf%25cf%258d%25ce%25b4%25ce%25b9%25ce%25b1%2520%25cf%2583%25ce%25b1%25cf%2582. is a suffix

**Comment by wwaites** [comment]
this appears to be caused by the combination of (1) lack of protocol at the head of the url and (2) the presence of a "." at the tail. minimal example to reproduce:

    $ giashardid www.reddit.com.
    2020/02/28 10:19:15 main.go:61: Error computing shard id: www.reddit.com. is a suffix
    $ giashardid 'http://www.reddit.com.'
    2020/02/28 10:20:05 main.go:61: Error computing shard id: www.reddit.com. is a suffix
    $ giashardid 'http://www.reddit.com/.'
    249

**Comment by kpu** [comment]
I think this is ultimately a bug in bitextor's WARC production for not having a protocol at the beginning but we've got legacy to deal with :-\.
