### ISSUE TITLE
Invalid hostnames. Accept or skip?

### ISSUE THREAD

**Issue by wwaites** [paracrawl/giashard#2]
What do we do about:

    folkloren_klub_ritam.artbf.com

Surprisingly, this actually manages to resolve despite `_` being an invalid character in a host name. Should we accept `_` in our kludge to resolve #1 or should we produce an error? Maybe it is best to apply Postel's Law...

**Comment by kpu** [comment]
Rare enough that we probably won't lose much data by dropping these.  But common enough that we can't die with an error message.
